apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: test-staging
  labels:
    app: ai-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        version: v1
    spec:
      containers:
      - name: ai-service
        image: plc-decompiler/ai-service:latest
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: SERVICE_PORT
          value: "8083"
        - name: AI_PROVIDER
          value: "gemini"
        - name: MODEL_CACHE_SIZE
          value: "1000"
        - name: GPU_ENABLED
          value: "false"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
